# Generated by Django 3.2.7 on 2021-09-15 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number', models.IntegerField()),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.industry')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dealer')),
            ],
        ),
    ]
